
import { Language } from './types';

export const COUNTRIES = [
  { code: 'CD', name: 'Rép. Dém. du Congo', flag: '🇨🇩' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'BE', name: 'Belgique', flag: '🇧🇪' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'CH', name: 'Suisse', flag: '🇨🇭' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲' },
  { code: 'CG', name: 'Congo-Brazzaville', flag: '🇨🇬' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳' },
  { code: 'HT', name: 'Haïti', flag: '🇭🇹' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MA', name: 'Maroc', flag: '🇲🇦' },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TN', name: 'Tunisie', flag: '🇹🇳' },
  { code: 'CN', name: 'Chine', flag: '🇨🇳' },
  { code: 'IN', name: 'Inde', flag: '🇮🇳' },
  { code: 'RU', name: 'Russie', flag: '🇷🇺' },
  { code: 'BR', name: 'Brésil', flag: '🇧🇷' },
  { code: 'DE', name: 'Allemagne', flag: '🇩🇪' },
  { code: 'IT', name: 'Italie', flag: '🇮🇹' },
  { code: 'ES', name: 'Espagne', flag: '🇪🇸' },
  { code: 'GB', name: 'Royaume-Uni', flag: '🇬🇧' },
  { code: 'NO', name: 'Norvège', flag: '🇳🇴' }
];

export const TRANSLATIONS = {
  fr: {
    nav: {
      play: "Jouer",
      ranking: "Classement",
      calendar: "Calendrier",
      profile: "Profil",
      tournaments: "Tournois",
      training: "Formation",
      news: "Annonces",
      chat: "Discussion",
      clubs: "Clubs",
      login: "Espace Membre",
      home: "Accueil",
      about: "À propos",
      contact: "Contact",
      logout: "Déconnexion",
      admin: "Administration"
    },
    common: {
      loading: "Chargement...",
      search: "Rechercher",
      filter: "Filtrer",
      all: "Tous",
      close: "Fermer",
      back: "Retour",
      days: "j",
      hours: "h",
      minutes: "m",
      seconds: "s"
    },
    admin: {
      title: "Tableau de Bord",
      subtitle: "Gérez les joueurs, les clubs et l'accès aux tournois.",
      super_title: "Contrôle Super Admin",
      tab_users: "Utilisateurs",
      tab_tournaments: "Tournois",
      tab_settings: "Paramètres Globaux",
      override_title: "Contrôles de Dérogation",
      allow_unpaid_title: "Autoriser les joueurs non payés",
      allow_unpaid_desc: "Si activé, les joueurs dont le statut est 'Non payé' peuvent s'inscrire et jouer aux tournois sans validation du club.",
      table_user: "Utilisateur",
      table_role: "Rôle",
      table_status: "Statut Paiement",
      table_actions: "Actions",
      paid: "Payé",
      unpaid: "Non Payé",
      edit: "Éditer",
      create_tournament: "Créer un Tournoi",
      form_name: "Nom du tournoi",
      form_desc: "Description courte",
      form_start: "Date de début",
      form_end: "Date de fin",
      form_max: "Max Joueurs",
      form_category: "Catégorie",
      form_submit: "Publier le Tournoi",
      success_create: "Tournoi créé avec succès !"
    },
    tournaments: {
      title: "Tournois",
      subtitle: "Affrontez le monde entier et grimpez au sommet.",
      filter_all: "Tous",
      filter_live: "En cours",
      filter_planned: "Prévus",
      filter_finished: "Terminés",
      status_live: "EN DIRECT",
      status_planned: "À VENIR",
      status_finished: "TERMINÉ",
      category_open: "Ouvert",
      category_validation: "Sur Validation",
      starts_in: "Commence dans :",
      remaining: "restant",
      ended: "Terminé",
      register: "S'inscrire",
      payment_required: "Paiement Club Requis",
      see_results: "Voir Résultats",
      players: "Joueurs",
      no_tournaments: "Aucun tournoi pour le moment. Revenez bientôt !"
    },
    ranking: {
      title: "Classement Global",
      rank: "Rang",
      player: "Joueur",
      country: "Pays",
      club: "Club",
      won: "Victoires",
      elo: "Elo",
      filter_country: "Pays",
      filter_gender: "Sexe",
      filter_year: "Né après",
      all_countries: "Tous les pays",
      all_genders: "Mixte",
      gender_m: "Hommes",
      gender_f: "Femmes",
      no_results: "Aucun joueur trouvé avec ces filtres."
    },
    auth: {
      login_title: "Bon retour parmi nous",
      register_title: "Créer un compte",
      email_label: "Adresse Email",
      password_label: "Mot de passe",
      confirm_password_label: "Confirmer le mot de passe",
      fullname_label: "Nom complet",
      country_label: "Pays",
      password_mismatch: "Les mots de passe ne correspondent pas.",
      submit_login: "Se connecter",
      submit_register: "S'inscrire",
      switch_to_register: "Pas encore de compte ? Créer un compte",
      switch_to_login: "Déjà membre ? Se connecter",
      error_generic: "Une erreur est survenue.",
      success_register: "Compte créé ! Veuillez vérifier votre email.",
      loading: "Chargement..."
    },
    landing: {
      hero_title: "La Stratégie à l'État Pur",
      hero_subtitle: "Rejoignez l'élite des échecs mondiaux. Affrontez des joueurs de tous horizons, analysez avec notre IA de pointe et dominez l'échiquier.",
      cta_primary: "Commencer à Jouer",
      cta_secondary: "Découvrir les Clubs",
      stats_players: "Joueurs Actifs",
      stats_matches: "Parties Jouées",
      stats_clubs: "Clubs Officiels",
      feature_1_title: "Compétition Intense",
      feature_1_desc: "Tournois quotidiens et classement ELO certifié.",
      feature_2_title: "Coach IA Avancé",
      feature_2_desc: "Une intelligence artificielle qui analyse vos coups en temps réel pour vous faire progresser.",
      feature_3_title: "Communauté Globale",
      feature_3_desc: "Connectez-vous avec des passionnés du monde entier.",
      footer_desc: "La plateforme d'échecs nouvelle génération. Développez votre potentiel, affrontez les meilleurs.",
      footer_links_title: "Liens Rapides",
      footer_legal_title: "Légal",
      footer_contact_title: "Nous contacter",
      rights: "Tous droits réservés."
    },
    home: {
      welcome: "Bienvenue sur ChessNetra",
      subtitle: "La plateforme d'échecs de référence.",
      cta_play: "Jouer une partie",
      cta_join: "Rejoindre un club"
    },
    game: {
      title: "Arène de Jeu",
      mode_online: "En Ligne",
      mode_computer: "Ordinateur",
      select_time: "Cadence de jeu",
      start: "Rechercher un adversaire",
      start_bot: "Défier ce Bot",
      opponent: "Adversaire",
      vs: "VS",
      bot_select: "Choisir un Adversaire Virtuel",
      game_active: "Partie en cours",
      resign: "Abandonner",
      draw: "Proposer Nulle",
      history: "Historique",
      players_online: "Joueurs en ligne",
      checkmate: "Échec et Mat !",
      draw_game: "Nulle",
      game_over: "Partie Terminée",
      white_wins_time: "Blancs gagnent (temps)",
      black_wins_time: "Noirs gagnent (temps)"
    },
    training: {
      title: "Académie ChessNetra",
      ai_coach: "Coach IA Virtuel",
      ask_coach: "Demander conseil à l'IA",
      placeholder: "Copiez le FEN ou décrivez la situation...",
      analyzing: "Analyse en cours...",
      advice_title: "Conseil du Coach",
      learning_path: "Parcours d'Apprentissage"
    }
  },
  en: {
    nav: {
      play: "Play",
      ranking: "Rankings",
      calendar: "Calendar",
      profile: "Profile",
      tournaments: "Tournaments",
      training: "Training",
      news: "News",
      chat: "Chat",
      clubs: "Clubs",
      login: "Member Area",
      home: "Home",
      about: "About",
      contact: "Contact",
      logout: "Sign Out",
      admin: "Administration"
    },
    common: {
      loading: "Loading...",
      search: "Search",
      filter: "Filter",
      all: "All",
      close: "Close",
      back: "Back",
      days: "d",
      hours: "h",
      minutes: "m",
      seconds: "s"
    },
    admin: {
      title: "Admin Dashboard",
      subtitle: "Manage players, clubs, and tournament access.",
      super_title: "Super Admin Control",
      tab_users: "Users",
      tab_tournaments: "Tournaments",
      tab_settings: "Global Settings",
      override_title: "Override Controls",
      allow_unpaid_title: "Allow Unpaid Players",
      allow_unpaid_desc: "If enabled, players with 'Unpaid' status can register and play in upcoming tournaments immediately without club verification.",
      table_user: "User",
      table_role: "Role",
      table_status: "Payment Status",
      table_actions: "Actions",
      paid: "Paid",
      unpaid: "Unpaid",
      edit: "Edit",
      create_tournament: "Create Tournament",
      form_name: "Tournament Name",
      form_desc: "Short Description",
      form_start: "Start Date",
      form_end: "End Date",
      form_max: "Max Players",
      form_category: "Category",
      form_submit: "Publish Tournament",
      success_create: "Tournament created successfully!"
    },
    tournaments: {
      title: "Tournaments",
      subtitle: "Compete globally and rise to the top.",
      filter_all: "All",
      filter_live: "Live",
      filter_planned: "Planned",
      filter_finished: "Finished",
      status_live: "LIVE NOW",
      status_planned: "UPCOMING",
      status_finished: "FINISHED",
      category_open: "Open",
      category_validation: "Validation",
      starts_in: "Starts in:",
      remaining: "remaining",
      ended: "Ended",
      register: "Register Now",
      payment_required: "Club Payment Required",
      see_results: "See Results",
      players: "Players",
      no_tournaments: "No tournaments yet. Check back soon!"
    },
    ranking: {
      title: "Global Rankings",
      rank: "Rank",
      player: "Player",
      country: "Country",
      club: "Club",
      won: "Won",
      elo: "Elo",
      filter_country: "Country",
      filter_gender: "Gender",
      filter_year: "Born after",
      all_countries: "All Countries",
      all_genders: "Mixed",
      gender_m: "Men",
      gender_f: "Women",
      no_results: "No players found with these filters."
    },
    auth: {
      login_title: "Welcome Back",
      register_title: "Create Account",
      email_label: "Email Address",
      password_label: "Password",
      confirm_password_label: "Confirm Password",
      fullname_label: "Full Name",
      country_label: "Country",
      password_mismatch: "Passwords do not match.",
      submit_login: "Sign In",
      submit_register: "Sign Up",
      switch_to_register: "No account? Create one",
      switch_to_login: "Already a member? Sign In",
      error_generic: "An error occurred.",
      success_register: "Account created! Please check your email.",
      loading: "Loading..."
    },
    landing: {
      hero_title: "Pure Strategy Unleashed",
      hero_subtitle: "Join the global chess elite. Compete internationally, analyze with advanced AI, and dominate the board.",
      cta_primary: "Start Playing",
      cta_secondary: "Discover Clubs",
      stats_players: "Active Players",
      stats_matches: "Matches Played",
      stats_clubs: "Official Clubs",
      feature_1_title: "Intense Competition",
      feature_1_desc: "Daily tournaments and certified ELO ranking.",
      feature_2_title: "Advanced AI Coach",
      feature_2_desc: "Artificial intelligence analyzing your moves in real-time to help you improve.",
      feature_3_title: "Global Community",
      feature_3_desc: "Connect with enthusiasts from around the world.",
      footer_desc: "The next-gen chess platform. Unlock your potential, play the best.",
      footer_links_title: "Quick Links",
      footer_legal_title: "Legal",
      footer_contact_title: "Contact Us",
      rights: "All rights reserved."
    },
    home: {
      welcome: "Welcome to ChessNetra",
      subtitle: "The leading chess platform.",
      cta_play: "Play a Game",
      cta_join: "Join a Club"
    },
    game: {
      title: "Game Arena",
      mode_online: "Online",
      mode_computer: "Computer",
      select_time: "Time Control",
      start: "Find Opponent",
      start_bot: "Challenge Bot",
      opponent: "Opponent",
      vs: "VS",
      bot_select: "Choose Virtual Opponent",
      game_active: "Game in Progress",
      resign: "Resign",
      draw: "Offer Draw",
      history: "History",
      players_online: "Players Online",
      checkmate: "Checkmate!",
      draw_game: "Draw",
      game_over: "Game Over",
      white_wins_time: "White wins on time",
      black_wins_time: "Black wins on time"
    },
    training: {
      title: "ChessNetra Academy",
      ai_coach: "Virtual AI Coach",
      ask_coach: "Ask AI for Advice",
      placeholder: "Paste FEN or describe position...",
      analyzing: "Analyzing...",
      advice_title: "Coach Advice",
      learning_path: "Learning Path"
    }
  }
};

export const MOCK_PLAYERS = [
  { id: '1', name: 'Magnus C.', elo: 2830, club: 'Norway Knights', club_id: 'c1', country: 'NO', gender: 'M', birth_year: 1990, tournaments_won: 145, role: 'member', is_paid_member: true },
  { id: '2', name: 'Hikaru N.', elo: 2780, club: 'Streamer Elite', club_id: 'c2', country: 'US', gender: 'M', birth_year: 1987, tournaments_won: 98, role: 'member', is_paid_member: true },
  { id: '3', name: 'Fabiano C.', elo: 2750, club: 'Italian Stallions', club_id: 'c3', country: 'IT', gender: 'M', birth_year: 1992, tournaments_won: 87, role: 'member', is_paid_member: true },
  { id: '4', name: 'Ding L.', elo: 2745, club: 'Eastern Dragons', club_id: 'c4', country: 'CN', gender: 'M', birth_year: 1992, tournaments_won: 92, role: 'member', is_paid_member: false },
  { id: '5', name: 'Hou Y.', elo: 2650, club: 'Eastern Dragons', club_id: 'c4', country: 'CN', gender: 'F', birth_year: 1994, tournaments_won: 45, role: 'member', is_paid_member: true },
  { id: '6', name: 'Judit P.', elo: 2675, club: 'Budapest Kings', club_id: 'c5', country: 'HU', gender: 'F', birth_year: 1976, tournaments_won: 60, role: 'admin', is_paid_member: true },
];

export const MOCK_BOTS = [
  { id: 'bot_1', name: 'Junior', elo: 400, description: 'Learning the rules. Makes random moves.', color: 'from-green-400 to-green-600', avatar: '👶' },
  { id: 'bot_2', name: 'Casual Carl', elo: 800, description: 'Plays occasionally. Blunders often.', color: 'from-teal-400 to-teal-600', avatar: '🙂' },
  { id: 'bot_3', name: 'Strategic Sarah', elo: 1200, description: 'Solid fundamentals. Hard to trick.', color: 'from-blue-400 to-blue-600', avatar: '🧐' },
  { id: 'bot_4', name: 'Tactical Tom', elo: 1600, description: 'Aggressive style. Watch your queen!', color: 'from-orange-400 to-orange-600', avatar: '⚔️' },
  { id: 'bot_5', name: 'Master Mind', elo: 2200, description: 'Fide Master level. Very few mistakes.', color: 'from-purple-400 to-purple-600', avatar: '🧙‍♂️' },
  { id: 'bot_6', name: 'Deep Blue', elo: 3000, description: 'Super Grandmaster engine. Unbeatable.', color: 'from-red-500 to-slate-900', avatar: '🤖' },
];

export const MOCK_ANNOUNCEMENTS = [
  { id: '1', title: 'Global Spring Championship', category: 'tournament', date: '2024-03-15', pinned: true, content: 'Register now for the biggest event of the season. Prize pool: $50,000. Open to all players worldwide.' },
  { id: '2', title: 'Goma International Open', category: 'tournament', date: '2024-04-20', pinned: false, content: 'Join us at the ChessNetra HQ in Goma, DRC, or participate online for this special hybrid event.' },
  { id: '3', title: 'Sicilian Defense Masterclass', category: 'training', date: '2024-03-10', pinned: false, content: 'Grandmaster analysis of the latest Sicilian trends.' },
];

// MOCK_TOURNAMENTS vider pour supprimer les tournois par défaut
export const MOCK_TOURNAMENTS = [];
