
import { Language } from './types';

export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫' },
  { code: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦' },
  { code: 'AL', name: 'Albanie', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algérie', flag: '🇩🇿' },
  { code: 'DE', name: 'Allemagne', flag: '🇩🇪' },
  { code: 'AD', name: 'Andorre', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'SA', name: 'Arabie saoudite', flag: '🇸🇦' },
  { code: 'AR', name: 'Argentine', flag: '🇦🇷' },
  { code: 'AM', name: 'Arménie', flag: '🇦🇲' },
  { code: 'AU', name: 'Australie', flag: '🇦🇺' },
  { code: 'AT', name: 'Autriche', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaïdjan', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  { code: 'BH', name: 'Bahreïn', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbade', flag: '🇧🇧' },
  { code: 'BE', name: 'Belgique', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯' },
  { code: 'BT', name: 'Bhoutan', flag: '🇧🇹' },
  { code: 'BY', name: 'Biélorussie', flag: '🇧🇾' },
  { code: 'MM', name: 'Birmanie', flag: '🇲🇲' },
  { code: 'BO', name: 'Bolivie', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosnie-Herzégovine', flag: '🇧🇦' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: 'BR', name: 'Brésil', flag: '🇧🇷' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgarie', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'KH', name: 'Cambodge', flag: '🇰🇭' },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'CV', name: 'Cap-Vert', flag: '🇨🇻' },
  { code: 'CF', name: 'Centrafrique', flag: '🇨🇫' },
  { code: 'CL', name: 'Chili', flag: '🇨🇱' },
  { code: 'CN', name: 'Chine', flag: '🇨🇳' },
  { code: 'CY', name: 'Chypre', flag: '🇨🇾' },
  { code: 'CO', name: 'Colombie', flag: '🇨🇴' },
  { code: 'KM', name: 'Comores', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo-Brazzaville', flag: '🇨🇬' },
  { code: 'CD', name: 'Congo-Kinshasa (RDC)', flag: '🇨🇩' },
  { code: 'KP', name: 'Corée du Nord', flag: '🇰🇵' },
  { code: 'KR', name: 'Corée du Sud', flag: '🇰🇷' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮' },
  { code: 'HR', name: 'Croatie', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'DK', name: 'Danemark', flag: '🇩🇰' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { code: 'DM', name: 'Dominique', flag: '🇩🇲' },
  { code: 'EG', name: 'Égypte', flag: '🇪🇬' },
  { code: 'AE', name: 'Émirats arabes unis', flag: '🇦🇪' },
  { code: 'EC', name: 'Équateur', flag: '🇪🇨' },
  { code: 'ER', name: 'Érythrée', flag: '🇪🇷' },
  { code: 'ES', name: 'Espagne', flag: '🇪🇸' },
  { code: 'EE', name: 'Estonie', flag: '🇪🇪' },
  { code: 'US', name: 'États-Unis', flag: '🇺🇸' },
  { code: 'ET', name: 'Éthiopie', flag: '🇪🇹' },
  { code: 'FJ', name: 'Fidji', flag: '🇫🇯' },
  { code: 'FI', name: 'Finlande', flag: '🇫🇮' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambie', flag: '🇬🇲' },
  { code: 'GE', name: 'Géorgie', flag: '🇬🇪' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'GR', name: 'Grèce', flag: '🇬🇷' },
  { code: 'GD', name: 'Grenade', flag: '🇬🇩' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼' },
  { code: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', name: 'Haïti', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HU', name: 'Hongrie', flag: '🇭🇺' },
  { code: 'IN', name: 'Inde', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonésie', flag: '🇮🇩' },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷' },
  { code: 'IE', name: 'Irlande', flag: '🇮🇪' },
  { code: 'IS', name: 'Islande', flag: '🇮🇸' },
  { code: 'IL', name: 'Israël', flag: '🇮🇱' },
  { code: 'IT', name: 'Italie', flag: '🇮🇹' },
  { code: 'JM', name: 'Jamaïque', flag: '🇯🇲' },
  { code: 'JP', name: 'Japon', flag: '🇯🇵' },
  { code: 'JO', name: 'Jordanie', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'KG', name: 'Kirghizistan', flag: '🇰🇬' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: 'XK', name: 'Kosovo', flag: '🇽🇰' },
  { code: 'KW', name: 'Koweït', flag: '🇰🇼' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'LV', name: 'Lettonie', flag: '🇱🇻' },
  { code: 'LB', name: 'Liban', flag: '🇱🇧' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', name: 'Libye', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', name: 'Lituanie', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MK', name: 'Macédoine du Nord', flag: '🇲🇰' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MY', name: 'Malaisie', flag: '🇲🇾' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MT', name: 'Malte', flag: '🇲🇹' },
  { code: 'MA', name: 'Maroc', flag: '🇲🇦' },
  { code: 'MH', name: 'Marshall', flag: '🇲🇭' },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺' },
  { code: 'MR', name: 'Mauritanie', flag: '🇲🇷' },
  { code: 'MX', name: 'Mexique', flag: '🇲🇽' },
  { code: 'FM', name: 'Micronésie', flag: '🇫🇲' },
  { code: 'MD', name: 'Moldavie', flag: '🇲🇩' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolie', flag: '🇲🇳' },
  { code: 'ME', name: 'Monténégro', flag: '🇲🇪' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibie', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', name: 'Népal', flag: '🇳評' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'NO', name: 'Norvège', flag: '🇳🇴' },
  { code: 'NZ', name: 'Nouvelle-Zélande', flag: '🇳🇿' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲' },
  { code: 'UG', name: 'Ouganda', flag: '🇺🇬' },
  { code: 'UZ', name: 'Ouzbékistan', flag: '🇺🇿' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'PW', name: 'Palaos', flag: '🇵🇼' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'NL', name: 'Pays-Bas', flag: '🇳🇱' },
  { code: 'PE', name: 'Pérou', flag: '🇵🇪' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'PL', name: 'Pologne', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { code: 'RO', name: 'Roumanie', flag: '🇷🇴' },
  { code: 'GB', name: 'Royaume-Uni', flag: '🇬🇧' },
  { code: 'RU', name: 'Russie', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'KN', name: 'Saint-Christophe-et-Niévès', flag: '🇰🇳' },
  { code: 'SM', name: 'Saint-Marin', flag: '🇸🇲' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', flag: '🇻🇨' },
  { code: 'LC', name: 'Sainte-Lucie', flag: '🇱🇨' },
  { code: 'SB', name: 'Salomon', flag: '🇸🇧' },
  { code: 'SV', name: 'Salvador', flag: '🇸🇻' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: 'ST', name: 'São Tomé-et-Prícipe', flag: '🇸🇹' },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbie', flag: '🇷🇸' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapour', flag: '🇸🇬' },
  { code: 'SK', name: 'Slovaquie', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovénie', flag: '🇸🇮' },
  { code: 'SO', name: 'Somalie', flag: '🇸🇴' },
  { code: 'SD', name: 'Soudan', flag: '🇸🇩' },
  { code: 'SS', name: 'Soudan du Sud', flag: '🇸🇸' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SE', name: 'Suède', flag: '🇸🇪' },
  { code: 'CH', name: 'Suisse', flag: '🇨🇭' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷' },
  { code: 'SY', name: 'Syrie', flag: '🇸🇾' },
  { code: 'TJ', name: 'Tadjikistan', flag: '🇹🇯' },
  { code: 'TW', name: 'Taïwan', flag: '🇹🇼' },
  { code: 'TZ', name: 'Tanzanie', flag: '🇹🇿' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩' },
  { code: 'CZ', name: 'Tchéquie', flag: '🇨🇿' },
  { code: 'TH', name: 'Thaïlande', flag: '🇹🇭' },
  { code: 'TL', name: 'Timor oriental', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinité-et-Tobago', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunisie', flag: '🇹🇳' },
  { code: 'TM', name: 'Turkménistan', flag: '🇹🇲' },
  { code: 'TR', name: 'Turquie', flag: '🇹🇷' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: 'VA', name: 'Vatican', flag: '🇻🇦' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'YE', name: 'Yémen', flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambie', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' }
];

export const TRANSLATIONS = {
  fr: {
    nav: {
      play: "Jouer",
      ranking: "Classement",
      calendar: "Calendrier",
      profile: "Profil",
      tournaments: "Tournois",
      training: "Formation",
      news: "Annonces",
      chat: "Discussion",
      clubs: "Clubs",
      login: "Espace Membre",
      home: "Accueil",
      about: "À propos",
      contact: "Contact",
      logout: "Déconnexion",
      admin: "Administration"
    },
    common: {
      loading: "Chargement...",
      search: "Rechercher",
      filter: "Filtrer",
      all: "Tous",
      close: "Fermer",
      back: "Retour",
      days: "j",
      hours: "h",
      minutes: "m",
      seconds: "s"
    },
    admin: {
      title: "Gestion Admin",
      subtitle: "Gérez les joueurs et les tournois ChessNetra.",
      tab_tournaments: "Tournois",
      tab_users: "Membres",
      create_tournament: "Créer un Tournoi",
      form_name: "Nom de l'événement",
      form_desc: "Description complète",
      form_submit: "Enregistrer les modifications",
      success_create: "Tournoi enregistré avec succès !",
      edit_tournament: "Modifier le Tournoi"
    },
    game: {
      title: "Arène de Jeu",
      select_time: "Choisir une Cadence",
      start: "Chercher un Adversaire",
      mode_online: "En Ligne",
      mode_computer: "Contre l'Ordinateur",
      bullet: "Ultra-Rapide (1-2 min)",
      blitz: "Éclair (3-5 min)",
      rapid: "Standard (10+ min)",
      difficulty_easy: "Débutant",
      difficulty_medium: "Intermédiaire",
      difficulty_hard: "Maître"
    },
    landing: {
      hero_title: "La Stratégie à l'État Pur.",
      hero_subtitle: "Rejoignez la plus grande communauté d'échecs en Afrique centrale. Jouez, apprenez et affrontez les meilleurs.",
      cta_primary: "Commencer à jouer",
      cta_secondary: "Découvrir les clubs",
      stats_players: "Joueurs actifs",
      stats_matches: "Parties jouées",
      stats_clubs: "Clubs officiels",
      feature_1_title: "Compétition",
      feature_1_desc: "Participez à des tournois quotidiens avec des prix réels.",
      feature_2_title: "Académie",
      feature_2_desc: "Améliorez votre jeu avec nos coachs certifiés.",
      feature_3_title: "Communauté",
      feature_3_desc: "Connectez-vous avec des passionnés partout dans le monde.",
      footer_desc: "ChessNetra est la plateforme leader pour le développement des échecs en RDC.",
      footer_links_title: "Liens rapides",
      footer_contact_title: "Contact",
      rights: "Tous droits réservés."
    },
    auth: {
      login_title: "Bon retour !",
      register_title: "Créer un compte",
      email_label: "Adresse Email",
      password_label: "Mot de passe",
      confirm_password_label: "Confirmer le mot de passe",
      fullname_label: "Nom complet",
      country_label: "Pays",
      submit_login: "Se connecter",
      submit_register: "S'inscrire",
      switch_to_register: "Pas de compte ? S'inscrire",
      switch_to_login: "Déjà membre ? Se connecter",
      error_generic: "Une erreur est survenue.",
      password_mismatch: "Les mots de passe ne correspondent pas.",
      success_register: "Compte créé ! Veuillez vous connecter."
    }
  },
  en: {
    nav: {
      play: "Play",
      ranking: "Rankings",
      calendar: "Calendar",
      profile: "Profile",
      tournaments: "Tournaments",
      training: "Training",
      news: "News",
      chat: "Chat",
      clubs: "Clubs",
      login: "Member Area",
      home: "Home",
      about: "About",
      contact: "Contact",
      logout: "Sign Out",
      admin: "Administration"
    },
    common: {
      loading: "Loading...",
      search: "Search",
      filter: "Filter",
      all: "All",
      close: "Close",
      back: "Back",
      days: "d",
      hours: "h",
      minutes: "m",
      seconds: "s"
    },
    admin: {
      title: "Admin Panel",
      subtitle: "Manage ChessNetra players and events.",
      tab_tournaments: "Tournaments",
      tab_users: "Members",
      create_tournament: "Create Tournament",
      form_name: "Event Name",
      form_desc: "Full Description",
      form_submit: "Save Changes",
      success_create: "Tournament saved successfully!",
      edit_tournament: "Edit Tournament"
    },
    game: {
      title: "Game Arena",
      select_time: "Choose Time Control",
      start: "Find Opponent",
      mode_online: "Online",
      mode_computer: "Vs Computer",
      bullet: "Ultra-Fast (1-2 min)",
      blitz: "Blitz / Quick (3-5 min)",
      rapid: "Standard (10+ min)",
      difficulty_easy: "Beginner",
      difficulty_medium: "Intermediate",
      difficulty_hard: "Master"
    },
    landing: {
      hero_title: "Strategy in its Purest Form.",
      hero_subtitle: "Join the largest chess community in Central Africa. Play, learn and face the best.",
      cta_primary: "Start playing",
      cta_secondary: "Explore clubs",
      stats_players: "Active players",
      stats_matches: "Games played",
      stats_clubs: "Official clubs",
      feature_1_title: "Competition",
      feature_1_desc: "Join daily tournaments with real prizes.",
      feature_2_title: "Academy",
      feature_2_desc: "Level up your game with certified coaches.",
      feature_3_title: "Community",
      feature_3_desc: "Connect with enthusiasts around the globe.",
      footer_desc: "ChessNetra is the leading platform for chess development in DRC.",
      footer_links_title: "Quick links",
      footer_contact_title: "Contact",
      rights: "All rights reserved."
    },
    auth: {
      login_title: "Welcome back!",
      register_title: "Create an account",
      email_label: "Email Address",
      password_label: "Password",
      confirm_password_label: "Confirm Password",
      fullname_label: "Full Name",
      country_label: "Country",
      submit_login: "Sign In",
      submit_register: "Sign Up",
      switch_to_register: "No account? Sign up",
      switch_to_login: "Already a member? Sign in",
      error_generic: "An error occurred.",
      password_mismatch: "Passwords do not match.",
      success_register: "Account created! Please log in."
    }
  }
};

export const MOCK_BOTS = [
  { id: 'bot_1', name: 'Le Débutant', elo: 400, description: 'Fait beaucoup de gaffes. Idéal pour commencer.', avatar: '👶', level: 'easy' },
  { id: 'bot_2', name: 'Zéro Fautes', elo: 800, description: 'Un peu plus solide, commence à punir les erreurs.', avatar: '🙂', level: 'easy' },
  { id: 'bot_3', name: 'Tactique Boy', elo: 1200, description: 'Attention aux fourchettes et aux clouages !', avatar: '🧐', level: 'medium' },
  { id: 'bot_4', name: 'Sarah G.', elo: 1450, description: 'Style agressif, elle adore sortir sa dame tôt.', avatar: '💁‍♀️', level: 'medium' },
  { id: 'bot_5', name: 'Stockfish Lite', elo: 1800, description: 'Une intelligence artificielle redoutable.', avatar: '🤖', level: 'hard' },
  { id: 'bot_6', name: 'Magnus Bot', elo: 2850, description: 'Le champion du monde virtuel. Bonne chance.', avatar: '🐐', level: 'hard' },
  { id: 'bot_7', name: 'Kaspar Bot', elo: 2600, description: 'Attaque constante sur le roi.', avatar: '🐯', level: 'hard' },
  { id: 'bot_8', name: 'Le Professeur', elo: 1600, description: 'Un jeu de position impeccable.', avatar: '👨‍🏫', level: 'medium' },
  { id: 'bot_9', name: 'Kévin', elo: 600, description: 'Joueur impulsif, souvent amusant.', avatar: '🤠', level: 'easy' },
];
